### ISSUE TITLE
Bug: Don't log in

### ISSUE THREAD

**Issue by TheEdaL06** [Botrixlist/botrix#10]
**Describe the bug**
The error is that it does not redirect to the main page after logging in, the browser sends an error saying that it cannot access the page

**How To Reproduce**
1. Clone the repository
2. Modify the config.json
3. Edit the lines mentioned in the repository of add.ejs and edit.ejs
4. Install dependencies
5. Add the redirects in Discord
6. Run npm start
7. Click on login, authorize and then the error
 
**Expected behavior**
Well, log in to the page

**Environment (add if possible)**
* Node.js version: v12.18.4
* Environment: Windows 10 Pro 64 bits

**Additional information & screenshots**
![image](https://user-images.githubusercontent.com/31509039/103768191-6182bc00-5022-11eb-93d9-698f713f6be7.png)
![image](https://user-images.githubusercontent.com/31509039/103768315-8d05a680-5022-11eb-9125-5e59a3cbb7bf.png)

**Comment by WaltDisneyWorld** [comment]
Is your discord oauth correct?

**Comment by dylanjamesdev** [comment]
Yes we use discord oauth through passport. I’ll get back with you soon with a translated guide on how to get everything up and running. :)

**Comment by WindowsCmd** [comment]
Hello, i see in your browser that the server is not responding. are you sure that you are using the right port and address?

**Comment by dylanjamesdev** [comment]
@WindowsCmd Botrix is running for him but there’s a language barrier, I think it’s a port issue because he DM’d me screenshots and there’s no actual errors. He speaks Spanish primarily.
