### ISSUE TITLE
SKU BTX Issue

### ISSUE THREAD

**Issue by WaltDisneyWorld** [Botrixlist/botrix#11]
When you select  some amount of coins to buy, it doesn't show up in your cart

**Comment by dylanjamesdev** [comment]
Did you setup the SKU database correctly? It works on my end. :)

**Comment by dylanjamesdev** [comment]
Please use something like MongoDB Compass to add a SKU table with the following options. 

<img width="156" alt="Screen Shot 2021-01-11 at 4 20 51 PM" src="https://user-images.githubusercontent.com/55116398/104239819-1e14bd00-5429-11eb-8c3b-997681bf9657.png">
<img width="636" alt="Screen Shot 2021-01-11 at 4 20 48 PM" src="https://user-images.githubusercontent.com/55116398/104239823-1ead5380-5429-11eb-80bf-05db9883100e.png">

**Comment by WaltDisneyWorld** [comment]
Also. It says im not in the guild whn trying to add something, but I am.

**Comment by dylanjamesdev** [comment]
You need to run the bot separately with something like pm2 or nodemon. 

This file :) 
https://github.com/Botrixlist/botrix/blob/main/src/bot/src/index.js

**Comment by Craftzman7** [comment]
@dylanjamesdev is this done?

**Comment by WaltDisneyWorld** [comment]
@Craftzman7 I don't believe so, however the project currently **works**
