### ISSUE TITLE
Bug: Banner not uploading

### ISSUE THREAD

**Issue by Craftzman7** [Botrixlist/botrix#17]
**Describe the bug**
A banner does not upload after bot edit

**How To Reproduce**
1. Have a bot owned on the site
2. Edit the bot
3. Upload a banner
4. Submit
 
**Expected behavior**
Banner uploads

**Environment**
* Node.js version: 14.15.5

**Comment by dylanjamesdev** [comment]
@Craftzman7  Whats the image? Images are handled by the Botrix cdn so it’s either offline or too big :)

**Comment by Craftzman7** [comment]
Like the image name?
