### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by VortexDev20** [Botrixlist/botrix#18]
<a href="/bots/<%= bot[0].botid ? bot[0].botid  : "/restricted/mod?page=queue"%>"> <span class="fa-stack fa-lg pull-left"><i class="fa fa-check fa-stack-1x "></i></span>Quick Start Verification</a>

Cannot read property 'botid' of undefined

**Comment by dylanjamesdev** [comment]
That happens when there are no bots in the queue :)
