### ISSUE TITLE
Bot problem

### ISSUE THREAD

**Issue by GalackQSM** [Botrixlist/botrix#24]
I have a problem with the bot,
In fact I have permissions everywhere when I want to place an order he says "this command can only be used by authorized operators"

**Comment by WindowsCmd** [comment]
Do you have your id whitelisted in the config.json file?

**Comment by dylanjamesdev** [comment]
You need to fill out the configuration file properly. In there is a command and developer slot for IDs

**Comment by GalackQSM** [comment]
yes I filled everything

**Comment by WindowsCmd** [comment]
Open a ticket in the botrix discord server and we can further help you there.
