### ISSUE TITLE
problem bot

### ISSUE THREAD

**Issue by Unknowqlf** [Botrixlist/botrix#27]
I have a problem I have configured everything but the bots do not mache how to do please

**Comment by dylanjamesdev** [comment]
Do you mean the bot isn’t running? You need to run the bot separately.

**Comment by WaltDisneyWorld** [comment]
> I have a problem I have configured everything but the bots do not mache how to do please

Depends what your running on, but run the bots separately usually.

**Comment by ezywebca** [comment]
i can run this off repl bots need too be run separate unless one of lazy bums makes a all in one script to run both bots XD
