### ISSUE TITLE
Redirect error

### ISSUE THREAD

**Issue by lordm121** [Botrixlist/botrix#31]
I have problem on r
![Screenshot_20210501_174754_com android chrome](https://user-images.githubusercontent.com/74502300/116786085-99b47b80-aaa5-11eb-9b3e-61692a3305cc.jpg)
edirect and your support server link expered

**Comment by dylanjamesdev** [comment]
I think you should learn the basic fundamentals of the discord developer section before even attempting to run a project like this.
