### ISSUE TITLE
AppID

### ISSUE THREAD

**Issue by FORWENTV** [Botrixlist/botrix#32]
Hello, I cannot configure the appID field  please help me !!!!

**Comment by Awish-Senpai** [comment]
> Hello, I cannot configure the appID field please help me !!!!

Hey @FORWENTV, thanks for opening the issue. So, basically the what is called to be an "appID" is just the Client ID of your app, which looks somewhat like the picture attached below

![appID](https://user-images.githubusercontent.com/69074469/118352363-a94abe80-b593-11eb-972d-6755e71230df.png)

Just copy the appID of your app, and put it in the appID field in the config file!
Hope this helps, if this is what you meant.

**Comment by FORWENTV** [comment]
Thank you but also I have another problem I can not manage with the oauth2 discord redirection for so much in my config.json there is indeed the field is in my develloper discord also but it always puts me in invalid oauth2 .
![image](https://user-images.githubusercontent.com/77687249/118353007-cc11ae80-b564-11eb-95c5-fc42ba1ab498.png)
and config.json
![image](https://user-images.githubusercontent.com/77687249/118353058-ff543d80-b564-11eb-8250-b9578fd59017.png)

**Comment by FORWENTV** [comment]
@Awish-Senpai
