### ISSUE TITLE
Oauth2

### ISSUE THREAD

**Issue by FORWENTV** [Botrixlist/botrix#33]
I have another problem I can not manage with the oauth2 discord redirection for so much in my config.json there is indeed the field is in my develloper discord also but it always puts me in invalid oauth2 .
![image](https://user-images.githubusercontent.com/77687249/118353007-cc11ae80-b564-11eb-95c5-fc42ba1ab498.png)
and config.json
![image](https://user-images.githubusercontent.com/77687249/118353058-ff543d80-b564-11eb-8250-b9578fd59017.png)

**Comment by dylanjamesdev** [comment]
I think you should learn the basics of discord’s developer platform before trying to run a project at this scale.
