### ISSUE TITLE
Error help

### ISSUE THREAD

**Issue by DairyWeb3638077** [Botrixlist/botrix#37]
@Awish-Senpai @dylanjamesdev @WindowsCmd Idk who the owner of this project is but if you are the owner or you can help me with an error, Please dm me on discord. DairyWeb3638077#8556 (ID: 751159519190450186)

**Comment by dylanjamesdev** [comment]
Please add the error here.

**Comment by DairyWeb3638077** [comment]
ok so I ran `npm install` and got this

added 594 packages, and audited 1029 packages in 2m

1 package is looking for funding
  run `npm fund` for details

19 vulnerabilities (2 low, 5 moderate, 12 high)

To address issues that do not require attention, run:
  npm audit fix

To address all issues possible (including breaking changes), run:
  npm audit fix --force

Some issues need review, and may require choosing
a different dependency.

Run `npm audit` for details.
---------------------------------------------------
then i ran `npm audit fix` and got this

npm WARN audit fix y18n@4.0.0 node_modules/npm/node_modules/y18n
npm WARN audit fix y18n@4.0.0 is a bundled dependency of
npm WARN audit fix y18n@4.0.0 npm@6.14.11 at node_modules/npm
npm WARN audit fix y18n@4.0.0 It cannot be fixed automatically.
npm WARN audit fix y18n@4.0.0 Check for updates to the npm package.
npm WARN audit fix hosted-git-info@2.8.8 node_modules/npm/node_modules/hosted-git-info
npm WARN audit fix hosted-git-info@2.8.8 is a bundled dependency of
npm WARN audit fix hosted-git-info@2.8.8 npm@6.14.11 at node_modules/npm
npm WARN audit fix hosted-git-info@2.8.8 It cannot be fixed automatically.
npm WARN audit fix hosted-git-info@2.8.8 Check for updates to the npm package.
npm WARN audit fix ssri@6.0.1 node_modules/npm/node_modules/ssri
npm WARN audit fix ssri@6.0.1 is a bundled dependency of
npm WARN audit fix ssri@6.0.1 npm@6.14.11 at node_modules/npm
npm WARN audit fix ssri@6.0.1 It cannot be fixed automatically.
npm WARN audit fix ssri@6.0.1 Check for updates to the npm package.
 
added 12 packages, removed 28 packages, changed 52 packages, and audited 1013 packages in 30s
 
4 packages are looking for funding
  run `npm fund` for details
 
# npm audit report
 
markdown  *
Regular Expression Denial of Service - https://npmjs.com/advisories/1330
No fix available
node_modules/markdown
 
ws  5.0.0 - 5.2.2 || 6.0.0 - 6.2.1 || 7.0.0 - 7.4.5
Severity: moderate
Regular Expression Denial of Service - https://npmjs.com/advisories/1748
fix available via `npm audit fix --force`
Will install pm2@5.1.0, which is a breaking change
node_modules/@pm2/agent/node_modules/ws
  @pm2/agent  1.0.3 - 1.0.8
  Depends on vulnerable versions of ws
  node_modules/@pm2/agent
    pm2  4.5.2 - 4.5.6
    Depends on vulnerable versions of @pm2/agent
    node_modules/pm2
 
4 vulnerabilities (1 low, 3 moderate)
 
To address all issues possible (including breaking changes), run:
  npm audit fix --force
 
Some issues need review, and may require choosing
a different dependency.

**Comment by dylanjamesdev** [comment]
What’s the problem? That’s a normal report when you run an audit.

**Comment by DairyWeb3638077** [comment]
I shouldn't get that error when running `npm install` than `npm audit fix`. I have never gotten that error for any other project

**Comment by dylanjamesdev** [comment]
That’s not an error tho, it’s telling you the audit for the node modules… it’s not related to this project.

**Comment by DairyWeb3638077** [comment]
ok than when I run `npm start` I get this
```js
> botrix-rewrite@1.0.0 start
> node src/index.js

(node:11308) Warning: Accessing non-existent property 'MongoError' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:11308) Warning: Accessing non-existent property 'route' of module exports inside circular dependency
(node:11308) DeprecationWarning: Listening to events on the Db class has been deprecated and will be removed in the next major version.
Connected to database on mongodb+srv://discordbotserverlist:discordbotserverlist@cluster0.oojpt.mongodb.net/discordbotserverlist?retryWrites=true&w=majority
body-parser deprecated bodyParser: use individual json/urlencoded middlewares src\index.js:173:11
body-parser deprecated undefined extended: provide extended option node_modules\body-parser\index.js:105:29
MONGO IS CONNECTED AND READY
node:events:371
      throw er; // Unhandled 'error' event
      ^

Error: listen EADDRINUSE: address already in use :::80
    at Server.setupListenHandle [as _listen2] (node:net:1306:16)
    at listenInCluster (node:net:1354:12)
    at Server.listen (node:net:1441:7)
    at Function.listen (E:\botrix-main\node_modules\express\lib\application.js:618:24)
    at E:\botrix-main\src\index.js:180:7
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
Emitted 'error' event on Server instance at:
    at emitErrorNT (node:net:1333:8)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  code: 'EADDRINUSE',
  errno: -4091,
  syscall: 'listen',
  address: '::',
  port: 80
}
```

**Comment by DairyWeb3638077** [comment]
wait

**Comment by DairyWeb3638077** [comment]
nvm

**Comment by dylanjamesdev** [comment]
Something is using port 80, I suggest learning the basics of node.js before attempting to run something of this nature.

**Comment by DairyWeb3638077** [comment]
I got this 
```js
> botrix-rewrite@1.0.0 start
> node src/index.js

(node:23512) Warning: Accessing non-existent property 'MongoError' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
(node:23512) Warning: Accessing non-existent property 'route' of module exports inside circular dependency
(node:23512) DeprecationWarning: Listening to events on the Db class has been deprecated and will be removed in the next major version.
Connected to database on mongodb+srv://discordbotserverlist:discordbotserverlist@cluster0.oojpt.mongodb.net/discordbotserverlist?retryWrites=true&w=majority
body-parser deprecated bodyParser: use individual json/urlencoded middlewares src\index.js:173:11
body-parser deprecated undefined extended: provide extended option node_modules\body-parser\index.js:105:29
MONGO IS CONNECTED AND READY
Discord Client attached to express, logged in as: discord-bot-list#1830
BTX Internal Blockchian online and awaiting requests.
Botrix Network online.
discord-server-list#2163 Is online and tracking guilds!
E:\botrix-main\src\routes\index.js:78
    const botsize = req.app.get("client").guilds.cache.get("721282458708082713").members.cache.filter((m) => m.user.bot).size
                                                                                ^

TypeError: Cannot read property 'members' of undefined
    at E:\botrix-main\src\routes\index.js:78:81
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

**Comment by dylanjamesdev** [comment]
That’s a known error, it doesn’t matter and you can ignore it.

**Comment by DairyWeb3638077** [comment]
> Something is using port 80, I suggest learning the basics of node.js before attempting to run something of this nature.

yes i found that issue

**Comment by DairyWeb3638077** [comment]
> That’s a known error, it doesn’t matter and you can ignore it.

well it stopped the terminal

**Comment by dylanjamesdev** [comment]
Change the  “721282458708082713” to your guild ID in E:\botrix-main\src\routes\index.js:78. 

It probably didn’t stop the terminal, it probably had nothing else to console log.

**Comment by DairyWeb3638077** [comment]
So I hit login and it says Invalid OAuth2 redirect_url

**Comment by dylanjamesdev** [comment]
You’ll need to set the oauth url in discord. Read the instructions on the discord api portal for more info.

**Comment by DairyWeb3638077** [comment]
i did

**Comment by DairyWeb3638077** [comment]
in the server bot I set the OAuth url to http://disbotlist.gq/api/callback and in the bot bot I set the url to the server invite

**Comment by dylanjamesdev** [comment]
Check the routes and see what the callback is, the config file doesn’t set the callback it only passes it to discord.

**Comment by DairyWeb3638077** [comment]
https://i.gyazo.com/02312cac127ecbe9c6d54143185a6734.png

https://i.gyazo.com/c6ab75a473f10c3459da1eb304ba2f81.png

that is what i did in the dev portal

**Comment by dylanjamesdev** [comment]
You did the oauth wrong. I would read the docs on that more. Find the callback route, and your oauth link would be that. 

Yourwebsite.com/auth/callback or whatever it is, off the top of my head I don’t remember it.

**Comment by DairyWeb3638077** [comment]
> You did the oauth wrong. I would read the docs on that more. Find the callback route, and your oauth link would be that.
> 
> Yourwebsite.com/auth/callback or whatever it is, off the top of my head I don’t remember it.

I could not find the callback route @dylanjamesdev

**Comment by DairyWeb3638077** [comment]
also, can i get an invite to the support server?

**Comment by Anish-530** [comment]
> also, can i get an invite to the support server?

If you need anymore support you can have it here. Since our support server is no longer that active as it used to be. But here's the link https://discord.gg/ZyBAaMZN

**Comment by LucasB25** [comment]
This login concern and very persistent your discord does not work 

Lนcαѕ#7323

**Comment by dylanjamesdev** [comment]
If you're trying to run this and you cant find the callback route I suggest learning nodejs and express first
