### ISSUE TITLE
Error when adding bot

### ISSUE THREAD

**Issue by kristianrose** [Botrixlist/botrix#4]
**As i was designing the new interface, when adding bots on the website says that you need to join the support server even if they are in.**

**Comment by MaximKing1** [comment]
For me it works fine ...

**Comment by Awish-Senpai** [comment]
> **As i was designing the new interface, when adding bots on the website says that you need to join the support server even if they are in.**

Yes it does happen sometimes, but that's not if you are also in the server. Yes, when there's a new error instead of showing the actual error it shows the "You are not in the server" error which our team will be working on further more if needed. I will look into this matter for more 1 day and will come to a healthy conclusion.

**Comment by dylanjamesdev** [comment]
Heya @kristianrose 

Are you running the bot separately?

**Comment by kristianrose** [comment]
> Heya @kristianrose
> 
> Are you running the bot separately? Typically this happens when the bot is not in the guild to pull user info. However you will need to run the bot separately from the bots src folder with the regular index.js file.

what, can u explain in datails

**Comment by MaximKing1** [comment]
> > Heya @kristianrose
> > Are you running the bot separately? Typically this happens when the bot is not in the guild to pull user info. However you will need to run the bot separately from the bots src folder with the regular index.js file.
> 
> what, can u explain in datails

Well what he means is is the bot and website running as a separate process, so is the bot running as a seprate bot to the site. To run separately you could use PM2 and run as 2 different processors..

**Comment by dylanjamesdev** [comment]
Closing & marking as stale.
