### ISSUE TITLE
SKU database

### ISSUE THREAD

**Issue by AibersonDev** [Botrixlist/botrix#5]
I was testing and when I try to get btx and I give the option to pay with paypal, I get an error in the console that comes from the file with the address **src/routes/api/transactions/paypalPay.js** and this is the error: 
```js
(node:463) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'name' of null
```
The line is: 
```js
"name": item.name,
```

**Comment by dylanjamesdev** [comment]
Thank you, we will look into it as soon as possible. :) 

@WindowsCmd

**Comment by WindowsCmd** [comment]
Hello, I just want to double check that you have your database set up properly. Can you provide a screenshot?

**Comment by AibersonDev** [comment]
What part do you want to see the screenshot of?

**Comment by WindowsCmd** [comment]
From the error it seems you have not setup the SKU database properly... i will see if i can add something to the admin panel that allows for you to add items to the database.

**Comment by AibersonDev** [comment]
Ok :/

**Comment by dylanjamesdev** [comment]
@AibersonDev Please reference this thread 
#11

**Comment by VortexDev20** [comment]
Soo ?

**Comment by dylanjamesdev** [comment]
He never relied with Windows had asked him for, the ticket hasn’t had any activity so it was marked as stale and closed.
