### ISSUE TITLE
Heroku Port Question

### ISSUE THREAD

**Issue by WaltDisneyWorld** [Botrixlist/botrix#9]
THe program still isn't running. Can someone help?

**Comment by dylanjamesdev** [comment]
Sure, I'd be happy to help!

Please answer these questions:

**Describe the bug**
A description of what the bug is.

**How To Reproduce**
Steps to reproduce the behavior:
1.
2.
 
**Expected behavior**
A description of what you expected to happen.

**Environment (add if possible)**
* Node.js version: 

**Additional information & screenshots**
Add any other context or screenshots about the problem here.

**Comment by WaltDisneyWorld** [comment]
This is what I get when I try running the project:
```
2021-01-06T10:25:34.904173+00:00 app[web.1]:   code: 'EACCES',
2021-01-06T10:25:34.904174+00:00 app[web.1]:   errno: 'EACCES',
2021-01-06T10:25:34.904174+00:00 app[web.1]:   syscall: 'listen',
2021-01-06T10:25:34.904174+00:00 app[web.1]:   address: '0.0.0.0',
2021-01-06T10:25:34.904174+00:00 app[web.1]:   port: 80
2021-01-06T10:25:34.904174+00:00 app[web.1]: }````

**Comment by dylanjamesdev** [comment]
That error is saying you don’t have permission on your computer to use port 80, it it’s Linux try using sudo or root.

**Comment by WaltDisneyWorld** [comment]
Uh. .. It's heroku

**Comment by dylanjamesdev** [comment]
Ah, heroku is different as they pick the ports you can use internally. I know you have to set it up differently config wise. 

@WindowsCmd owo can you guide this lad?

**Comment by WaltDisneyWorld** [comment]
Ah. Thanks

**Comment by WaltDisneyWorld** [comment]
I recieved the same error when I tried repl.it

**Comment by dylanjamesdev** [comment]
Cloud hosting typically isn’t the best when it comes to nodejs projects in my experience. I know what both repl.it and heroku they use port proxies to keep everything clean so pretty much 80 isn’t really 80 and so on. We used to run our own version on heroku (before me), so I’m sure windows can point you in the right direction! :p 

Have you tried running it locally for testing purposes?

**Comment by WindowsCmd** [comment]
Heya, heroku does not use static ports. To get the port to use on heroku do `process.env.PORT`

**Comment by WaltDisneyWorld** [comment]
Thanks!

**Comment by WaltDisneyWorld** [comment]
Lemme fix it.

**Comment by WaltDisneyWorld** [comment]
How would I find the port however?

**Comment by WaltDisneyWorld** [comment]
I only see heroku run commands

**Comment by WindowsCmd** [comment]
In the file index.js replace `app.listen(80)` with `app.listen(process.end.port)`

**Comment by WaltDisneyWorld** [comment]
Thanks.

**Comment by WaltDisneyWorld** [comment]
IT's saying its online but web isn't showing up however.

**Comment by WaltDisneyWorld** [comment]
One wierd question. Site is staying in maintenance mode. I think that's an error.

**Comment by WaltDisneyWorld** [comment]
@WindowsCmd

**Comment by WaltDisneyWorld** [comment]
Fixed it myself.
